//! Native utilities exported via N-API for the Oh My Pi toolchain.
//!
//! # Overview
//! High-performance primitives for grep, file discovery, ANSI-aware text
//! measurement, syntax highlighting, HTML-to-Markdown conversion, and image
//! processing.
//!
//! # Example
//! ```ignore
//! use pi_natives::text::visible_width;
//!
//! let width = visible_width("hello");
//! assert_eq!(width, 5);
//! ```
//!
//! # Architecture
//! ```text
//! JS (packages/natives) -> N-API -> Rust modules (find/grep/html/highlight/image/text)
//! ```

#![allow(clippy::trailing_empty_array, reason = "generated by napi macro")]

pub mod find;
pub mod grep;
pub mod highlight;
pub mod html;
pub mod image;
pub mod keys;
pub mod shell;
pub mod text;
